name: Change Validation

"on":
  workflow_call:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test-suite:
    uses: ./.github/workflows/test-suite.yml
